### ISSUE TITLE
How to browserify emojimart? 

### ISSUE THREAD

**Issue by Montoya** [missive/emoji-mart#241]
Hello everyone, I'm trying to use this plugin on a webpage that I didn't build with React, just plain HTML & JS. As I understand it, I can include React & React DOM in my HTML head from unpkg, and then I can render a React component in a container, as long as the script to render the React component comes right after the HTML container.

What I can't figure out is how to actually webpack or browserify or whatever the plugin itself. I tried both and got stuck. To be more specific, I installed the plugin in my project directory with npm, then I installed browserify, created a file picker.js that imports React, React DOM and the plugin and renders the plugin in a container from my HTML. I then tried to browserify picker.js, but it complained about the import syntax being used. When I tried the same thing with Webpack, I got the same complaint.

I'm a noob with this stuff, I've never used anything like browserify or webpack before. I just want to get a bundled JS+CSS distribution I can include in my webpage so I can render this component. What am I missing?

**Comment by Montoya** [comment]
Update: Just to try a different tack, I decided to fork this plugin and clone it locally, then modify the contents of docs/webpack.config.js and run `webpack docs/` from the main directory (of course, after running `npm install`, `yarn build` in the main directory). Every time, I get the following error: 

```
ERROR in ./docs/index.js 34:11
Module parse failed: Unexpected token (34:11)
You may need an appropriate loader to handle this file type.
| 
|   render() {
>     return <div>
|       <div className="row">
|         <h1>Emoji Mart 🏬</h1>
```

When was the last time the docs folder was built? I have a feeling this config may be out of date.

**Comment by Montoya** [comment]
Still trying to get this working. I tried running Parcel on docs/index.html and I got the following error: 

```
🚨  /Users/Montoya/Documents/GitRepos/emoji-mart/docs/index.html: [BABEL] /Users/Montoya/Documents/GitRepos/emoji-mart/docs/index.html: Unknown option: base.parserOpts. Check out http://babeljs.io/docs/usage/options/ for more info
    at Logger.error (/Users/Montoya/Documents/GitRepos/emoji-mart/node_modules/babel-core/lib/transformation/file/logger.js:39:11)
    at OptionManager.mergeOptions (/Users/Montoya/Documents/GitRepos/emoji-mart/node_modules/babel-core/lib/transformation/file/options/option-manager.js:267:20)
    at OptionManager.init (/Users/Montoya/Documents/GitRepos/emoji-mart/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/Users/Montoya/Documents/GitRepos/emoji-mart/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/Users/Montoya/Documents/GitRepos/emoji-mart/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/Users/Montoya/Documents/GitRepos/emoji-mart/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at babel6 (/usr/local/lib/node_modules/parcel-bundler/src/transforms/babel/babel6.js:26:19)
```

**Comment by nolanlawson** [comment]
It looks like somehow you are importing from the `docs` directory. You'll want to import from the `dist` or `dist-es` directory instead. This is where the actual bundled JavaScript is: https://unpkg.com/emoji-mart@2.9.2/dist/
