### ISSUE TITLE
Block-scoped declaration

### ISSUE THREAD

**Issue by ricking06** [missive/emoji-mart#67]
```
emoji-mart/scripts/build-data.js:97
  for (let key in datum) {
       ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

**Comment by EtienneLem** [comment]
What’s your ` node --version`? Not sure what version that started to be supported, mine is `v7.9.0`

**Comment by ricking06** [comment]
it was v4 i upgraded now works fine
