### ISSUE TITLE
Support for React SSR

### ISSUE THREAD

**Issue by gbhrdt** [missive/emoji-mart#7]
Hi, nice component, but it does not seem to work with React server-side rendering, as it uses the `window` object, which is only available on the client.

	ReferenceError: window is not defined
	  at Object.get (/node_modules/emoji-mart/dist/emoji-mart.js:919:28)
	  at Object.defineProperty.value (/node_modules/emoji-mart/dist/emoji-mart.js:865:35)
	  at __webpack_require__ (/node_modules/emoji-mart/dist/emoji-mart.js:30:30)
	  at Object.defineProperty.value (/node_modules/emoji-mart/dist/emoji-mart.js:609:20)
	  at __webpack_require__ (/node_modules/emoji-mart/dist/emoji-mart.js:30:30)
	  at Object.defineProperty.value (/node_modules/emoji-mart/dist/emoji-mart.js:116:18)
	  at __webpack_require__ (/node_modules/emoji-mart/dist/emoji-mart.js:30:30)
	  at Object.defineProperty.value /node_modules/emoji-mart/dist/emoji-mart.js:64:20)
	  at __webpack_require__ (/node_modules/emoji-mart/dist/emoji-mart.js:30:30)
	  at Object.defineProperty.value (/node_modules/emoji-mart/dist/emoji-mart.js:50:18)

**Comment by EtienneLem** [comment]
See [#575 ](https://github.com/missive/emoji-mart/issues/575#issuecomment-1111323710), will add documentation soon.
