### ISSUE TITLE
Build in next failed

### ISSUE THREAD

**Issue by krajcikondra** [missive/emoji-mart#744]
Hi,

I am facing to following problem with build in next.js. Build failed with following error:

```
info  - Collecting page data .ReferenceError: $d03bf5953babc97e$import$1d20cf026fb5935d$2e2bcd8739ae039 is not defined
    at /home/myProfile/www/myprject/node_modules/emoji-mart/dist/main.js:1670:5
    at Object.<anonymous> (/home/myProfile/www/myprject/node_modules/emoji-mart/dist/main.js:1722:2)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/myProfile/www/myprject/node_modules/@emoji-mart/react/dist/main.js:2:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.79390 (/home/myProfile/www/myprject/.next/server/pages/_app.js:28286:18)
    at __webpack_require__ (/home/myProfile/www/myprject/.next/server/webpack-runtime.js:25:42)
    at Object.12523 (/home/myProfile/www/myprject/.next/server/chunks/959.js:8360:`

........

> Build error occurred
Error: Failed to collect page data for /
    at /home/myProfile/www/myprject/node_modules/next/dist/build/utils.js:916:15 {
  type: 'Error'
}

```

Can somebody hepl me? I have no idea what can be wrong.

**Comment by EtienneLem** [comment]
What version of `emoji-mart` are you using? We release **v5.3.3** just a few minutes ago; this issue should be fixed.

**Comment by krajcikondra** [comment]
I am usining version v5.3.2. After update to v5.3.3 it works :+1: 
Thanks
