### ISSUE TITLE
Updating locale property with custom categories causes an error

### ISSUE THREAD

**Issue by sjsanc** [missive/emoji-mart#794]
Changing the locale prop with custom emojis loaded triggers the below error after an interaction. Removing the `custom` property prevents this issue, so I'm assuming it's failing to load the custom category after a reload. It doesn't happen with all locales; for example, setting it to English after a reload never breaks. 

```
Picker.tsx:893 Uncaught (in promise) TypeError: Cannot destructure property 'root' of 'this.refs.categories.get(...)' as it is undefined.
    at Picker.tsx:893:1
    at Array.map (<anonymous>)
    at $89bd6bb200cc8fef$export$2e2bcd8739ae039.renderCategories (Picker.tsx:892:1)
    at $89bd6bb200cc8fef$export$2e2bcd8739ae039.render (Picker.tsx:1119:1)
    at $fb96b826c0c5f37a$var$j (index.js:171:1)
    at component.js:221:1
    at Array.some (<anonymous>)
    at $fb96b826c0c5f37a$var$g (component.js:216:1)
(anonymous) @ Picker.tsx:893
...
```

The component itself: 
```js 
    <Picker
      data={data}
      custom={[customGithubEmojis]}
      categoryIcons={customEmojiCategories}
      onEmojiSelect={onEmojiSelect}
      theme={mode === "dark" ? "dark" : "light"}
      sx={{ pt: "1", pb: "1" }}
      locale={locale}
    />
```

**Comment by rickstaa** [comment]
@sjsanc I could not reproduce your problems when I worked on https://github.com/rickstaa/github-emoji-picker/pull/63. Is this still an error in emoji-mart, or could it be something in our repository?

**Comment by syusui-s** [comment]
I've run into the same issue where using either the `i18n` or `custom` property seems to be causing problems.

My application uses the emoji-mart `Picker` component inside a popup component. Therefore, the Picker is instantiated multiple times and then unmounted whenever a popup closes.

The first time a popup opens, custom emojis and i18n functionalities worked as expected. However, for any subsequent popups, the Picker breaks. I only see the first few dozen emojis, the rest don't show up, and the custom emoji tab is missing.

I got the following error:

```
Uncaught (in promise) TypeError: this.refs.categories.get(...) is undefined
    children Picker.tsx:893
    renderCategories Picker.tsx:892
    render Picker.tsx:1121
```

To reproduce:

```javascript
  const picker = new Picker({
    data: async () => {
      const response = await fetch('https://cdn.jsdelivr.net/npm/@emoji-mart/data');
      return response.json();
    },
    i18n: async () => {
      const response = await fetch('https://cdn.jsdelivr.net/npm/@emoji-mart/data/i18n/ja.json');
      return response.json();
    },
    custom: [
      {
        id: 'custom',
        name: 'Custom Emojis',
        emojis: customEmojis,
      },
    ],
    locale: 'ja',
    onClickOutside: () => picker.remove(),
  });
```

The workaround is to remove the `i18n` property or removing the `custom` property.

I'm not sure if this is directly related, but I've heard of a similar issue occurring when the `custom` property is used with multiple `Picker` instances at the same time.

**Comment by ertrzyiks** [comment]
I created a sandbox with the bug reproduced in the simplest possible way: https://codesandbox.io/p/sandbox/gallant-benz-5dj4ht?file=%2Fsrc%2FApp.js%3A5%2C40

Looks like it happens because of the `Data` object [is a singleton](https://github.com/missive/emoji-mart/blob/21a2708be931c0dd16d6d0e96b47a45503576ac5/packages/emoji-mart/src/config.ts#L12) and that doesn't play nicely with multiple instances of the Picker at the same page.

**Comment by ThenTech** [comment]
@ertrzyiks Is it expected in your sandbox that the error gets thrown when interacting (hovering etc.) with the top Picker, the one that does _not_ have custom emojis?

I ran into the same problem when the `locale` was different from English. If `locale` (and `i18n`) is not specified, the picker will default to the English strings which are already included in the build. However, when specifying a different locale, it will await the fetch on the CDN.

In my case, while this fetch was still going on, hovering over an emoji causes the initial error. This is because the picker tries to render the custom categories and emojis in the UI (or at least prepare the row offsets etc.), but this is actually dependent on the locale being available. (Because it wants to get the translated string for the "Custom" category)
So while the locale is being fetched in init, the custom categories have not been made yet (even though the custom emojis already exist). But the code already tries to add the divs in the UI for the custom categories, even though the internal state `this.refs.categories` does not contain those categories yet. So when performing `this.refs.categories.get` with an id of a custom category, the error is thrown.

The solution, which seems to work for me, is to just import the locales I need manually, and provide those to **both** the `init` function (as e.g. `locale: "fr", i18n: i18n_fr` from `@emoji-mart/data/i18n/fr.json`) and to the _Picker_ component as well. That way, it won't try to fetch them, and the custom categories are shown properly from the start.
