### ISSUE TITLE
Getting error when using in create-react-app after building

### ISSUE THREAD

**Issue by bhanu-manthry** [missive/emoji-mart#94]
Hi
I'm trying to use emoji-mart in the project built with create-react-app, it is working fine in development but while running the production build it is showing the following error
`Uncaught TypeError: Cannot read property 'custom' of undefined
    at n (http://localhost:5000/static/js/main.4be574a7.js:1:788065)
    at r (http://localhost:5000/static/js/main.4be574a7.js:1:125795)
    at e (http://localhost:5000/static/js/main.4be574a7.js:1:126162)
    at http://localhost:5000/static/js/main.4be574a7.js:1:121536
    at Array.map (native)
    at a.value (http://localhost:5000/static/js/main.4be574a7.js:1:121503)
    at r._renderValidatedComponentWithoutOwnerOrContext (http://localhost:5000/static/js/main.4be574a7.js:1:848718)
    at r._renderValidatedComponent (http://localhost:5000/static/js/main.4be574a7.js:1:848845)
    at r.performInitialMount (http://localhost:5000/static/js/main.4be574a7.js:1:844684)
    at r.mountComponent (http://localhost:5000/static/js/main.4be574a7.js:1:843730)`

and nothing is showed on screen

**Comment by EtienneLem** [comment]
Any chance you could temporarily have source maps enabled? Would help figure out where the error is coming from.

**Comment by bhanu-manthry** [comment]
I figured out that I am getting that error when I set the perLine prop to the <Picker />, but sometimes it is working fine and sometimes error occurs when I set the perLine props. It is working fine when I don't set perLine prop.
